require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.1
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'
    - 'Gemfile'
    - 'db/schema.rb'
    - 'db/migrate/*'

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false